//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLSoccerCOM.ProService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlsoccer.com/", ConfigurationName="ProService.FootballDataSoap")]
    public interface FootballDataSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetHistoricMatchesByTeamAndDateInterval", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetHistoricMatchesByTeamAndDateInterval(string ApiKey, string teamId, string startDateString, string endDateString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetFixturesByDateIntervalAndTeam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetFixturesByDateIntervalAndTeam(string ApiKey, string startDateString, string endDateString, string teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetFixturesByLeagueAndSeason", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetFixturesByLeagueAndSeason(string ApiKey, string seasonDateString, string league);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetHistoricMatchesByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetHistoricMatchesByID(string ApiKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetHistoricMatchesByFixtureMatchID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetHistoricMatchesByFixtureMatchID(string ApiKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetTopScorersByLeagueAndSeason", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetTopScorersByLeagueAndSeason(string ApiKey, string league, string seasonDateString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetTopScorersByGroupId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetTopScorersByGroupId(string ApiKey, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetHistoricMatchesByLeagueAndDateInterval", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetHistoricMatchesByLeagueAndDateInterval(string ApiKey, string league, string startDateString, string endDateString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetHistoricMatchesByLeagueAndSeason", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetHistoricMatchesByLeagueAndSeason(string ApiKey, string league, string seasonDateString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetHistoricMatchesByTeamsAndDateInterval", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetHistoricMatchesByTeamsAndDateInterval(string ApiKey, string team1Id, string team2Id, string startDateString, string endDateString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetFixturesByDateInterval", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetFixturesByDateInterval(string ApiKey, string startDateString, string endDateString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetFixturesByDateIntervalAndLeague", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetFixturesByDateIntervalAndLeague(string league, string ApiKey, string startDateString, string endDateString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetAllTeams", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAllTeams(string ApiKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetAllLeagues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAllLeagues(string ApiKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetAllGroupsByLeagueAndSeason", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAllGroupsByLeagueAndSeason(string ApiKey, string league, string seasonDateString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetLeagueStandingsBySeason", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLeagueStandingsBySeason(string ApiKey, string league, string seasonDateString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetCupStandingsByGroupId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetCupStandingsByGroupId(string ApiKey, int group_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetAllTeamsByLeagueAndSeason", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAllTeamsByLeagueAndSeason(string ApiKey, string league, string seasonDateString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetEarliestMatchDatePerLeague", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetEarliestMatchDatePerLeague(string ApiKey, string league);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetLiveScore", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLiveScore(string ApiKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetLiveScoreByLeague", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLiveScoreByLeague(string ApiKey, string league);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetPlayersByTeam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetPlayersByTeam(string ApiKey, string teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetPlayerById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetPlayerById(string ApiKey, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetTeam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetTeam(string ApiKey, string teamName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetOddsByFixtureMatchId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetOddsByFixtureMatchId(string ApiKey, string fixtureMatch_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetOddsByFixtureMatchId2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetOddsByFixtureMatchId2(string ApiKey, string fixtureMatch_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetAllOddsByFixtureMatchId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAllOddsByFixtureMatchId(string ApiKey, int fixtureMatch_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/GetNextMatchOddsByLeague", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetNextMatchOddsByLeague(string ApiKey, string league);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlsoccer.com/CheckApiKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckApiKey(string ApiKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FootballDataSoapChannel : XMLSoccerCOM.ProService.FootballDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FootballDataSoapClient : System.ServiceModel.ClientBase<XMLSoccerCOM.ProService.FootballDataSoap>, XMLSoccerCOM.ProService.FootballDataSoap {
        
        public FootballDataSoapClient() {
        }
        
        public FootballDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FootballDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FootballDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FootballDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode GetHistoricMatchesByTeamAndDateInterval(string ApiKey, string teamId, string startDateString, string endDateString) {
            return base.Channel.GetHistoricMatchesByTeamAndDateInterval(ApiKey, teamId, startDateString, endDateString);
        }
        
        public System.Xml.XmlNode GetFixturesByDateIntervalAndTeam(string ApiKey, string startDateString, string endDateString, string teamId) {
            return base.Channel.GetFixturesByDateIntervalAndTeam(ApiKey, startDateString, endDateString, teamId);
        }
        
        public System.Xml.XmlNode GetFixturesByLeagueAndSeason(string ApiKey, string seasonDateString, string league) {
            return base.Channel.GetFixturesByLeagueAndSeason(ApiKey, seasonDateString, league);
        }
        
        public System.Xml.XmlNode GetHistoricMatchesByID(string ApiKey, int Id) {
            return base.Channel.GetHistoricMatchesByID(ApiKey, Id);
        }
        
        public System.Xml.XmlNode GetHistoricMatchesByFixtureMatchID(string ApiKey, int Id) {
            return base.Channel.GetHistoricMatchesByFixtureMatchID(ApiKey, Id);
        }
        
        public System.Xml.XmlNode GetTopScorersByLeagueAndSeason(string ApiKey, string league, string seasonDateString) {
            return base.Channel.GetTopScorersByLeagueAndSeason(ApiKey, league, seasonDateString);
        }
        
        public System.Xml.XmlNode GetTopScorersByGroupId(string ApiKey, int groupId) {
            return base.Channel.GetTopScorersByGroupId(ApiKey, groupId);
        }
        
        public System.Xml.XmlNode GetHistoricMatchesByLeagueAndDateInterval(string ApiKey, string league, string startDateString, string endDateString) {
            return base.Channel.GetHistoricMatchesByLeagueAndDateInterval(ApiKey, league, startDateString, endDateString);
        }
        
        public System.Xml.XmlNode GetHistoricMatchesByLeagueAndSeason(string ApiKey, string league, string seasonDateString) {
            return base.Channel.GetHistoricMatchesByLeagueAndSeason(ApiKey, league, seasonDateString);
        }
        
        public System.Xml.XmlNode GetHistoricMatchesByTeamsAndDateInterval(string ApiKey, string team1Id, string team2Id, string startDateString, string endDateString) {
            return base.Channel.GetHistoricMatchesByTeamsAndDateInterval(ApiKey, team1Id, team2Id, startDateString, endDateString);
        }
        
        public System.Xml.XmlNode GetFixturesByDateInterval(string ApiKey, string startDateString, string endDateString) {
            return base.Channel.GetFixturesByDateInterval(ApiKey, startDateString, endDateString);
        }
        
        public System.Xml.XmlNode GetFixturesByDateIntervalAndLeague(string league, string ApiKey, string startDateString, string endDateString) {
            return base.Channel.GetFixturesByDateIntervalAndLeague(league, ApiKey, startDateString, endDateString);
        }
        
        public System.Xml.XmlNode GetAllTeams(string ApiKey) {
            return base.Channel.GetAllTeams(ApiKey);
        }
        
        public System.Xml.XmlNode GetAllLeagues(string ApiKey) {
            return base.Channel.GetAllLeagues(ApiKey);
        }
        
        public System.Xml.XmlNode GetAllGroupsByLeagueAndSeason(string ApiKey, string league, string seasonDateString) {
            return base.Channel.GetAllGroupsByLeagueAndSeason(ApiKey, league, seasonDateString);
        }
        
        public System.Xml.XmlNode GetLeagueStandingsBySeason(string ApiKey, string league, string seasonDateString) {
            return base.Channel.GetLeagueStandingsBySeason(ApiKey, league, seasonDateString);
        }
        
        public System.Xml.XmlNode GetCupStandingsByGroupId(string ApiKey, int group_Id) {
            return base.Channel.GetCupStandingsByGroupId(ApiKey, group_Id);
        }
        
        public System.Xml.XmlNode GetAllTeamsByLeagueAndSeason(string ApiKey, string league, string seasonDateString) {
            return base.Channel.GetAllTeamsByLeagueAndSeason(ApiKey, league, seasonDateString);
        }
        
        public System.Xml.XmlNode GetEarliestMatchDatePerLeague(string ApiKey, string league) {
            return base.Channel.GetEarliestMatchDatePerLeague(ApiKey, league);
        }
        
        public System.Xml.XmlNode GetLiveScore(string ApiKey) {
            return base.Channel.GetLiveScore(ApiKey);
        }
        
        public System.Xml.XmlNode GetLiveScoreByLeague(string ApiKey, string league) {
            return base.Channel.GetLiveScoreByLeague(ApiKey, league);
        }
        
        public System.Xml.XmlNode GetPlayersByTeam(string ApiKey, string teamId) {
            return base.Channel.GetPlayersByTeam(ApiKey, teamId);
        }
        
        public System.Xml.XmlNode GetPlayerById(string ApiKey, int playerId) {
            return base.Channel.GetPlayerById(ApiKey, playerId);
        }
        
        public System.Xml.XmlNode GetTeam(string ApiKey, string teamName) {
            return base.Channel.GetTeam(ApiKey, teamName);
        }
        
        public System.Xml.XmlNode GetOddsByFixtureMatchId(string ApiKey, string fixtureMatch_Id) {
            return base.Channel.GetOddsByFixtureMatchId(ApiKey, fixtureMatch_Id);
        }
        
        public System.Xml.XmlNode GetOddsByFixtureMatchId2(string ApiKey, string fixtureMatch_Id) {
            return base.Channel.GetOddsByFixtureMatchId2(ApiKey, fixtureMatch_Id);
        }
        
        public System.Xml.XmlNode GetAllOddsByFixtureMatchId(string ApiKey, int fixtureMatch_Id) {
            return base.Channel.GetAllOddsByFixtureMatchId(ApiKey, fixtureMatch_Id);
        }
        
        public System.Xml.XmlNode GetNextMatchOddsByLeague(string ApiKey, string league) {
            return base.Channel.GetNextMatchOddsByLeague(ApiKey, league);
        }
        
        public string CheckApiKey(string ApiKey) {
            return base.Channel.CheckApiKey(ApiKey);
        }
    }
}
